name: run-fuzzing
run-name: Fuzzing system test triggered by @${{ github.actor }}
on: [workflow_dispatch, push]

jobs:
    run-aerialist-fuzzer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker-practice/actions-setup-docker@master
              timeout-minutes: 5
            - name: Create Docker Image and Run Tests
              run: |
                cd ./snippets
                sudo docker build -t aerialist .
                cd ..
                echo image built
                sudo docker run --env-file .env -d aerialist 
                echo image ran, now exec
                sudo docker exec $(docker run --env-file .env -d aerialist) python3 cli.py generate case_studies/mission1.yaml 4
            