name: run-fuzzing
run-name: Fuzzing system test triggered by @${{ github.actor }}
on: [workflow_dispatch, push]

jobs:
    run-aerialist-fuzzer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker-practice/actions-setup-docker@master
              timeout-minutes: 5
            - run: |
                cd ./snippets
                sudo docker build -t aerialist .
                cd ..
                sudo docker exec $(docker run --env-file .env -d aerialist) bash
                python3 cli.py generate snippets/case_studies/mission1.yaml 4
            