name: run-fuzzing
run-name: Fuzzing system test triggered by @${{ github.actor }}
on: workflow_dispatch

jobs:
    run-aerialist-fuzzer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker-practice/actions-setup-docker@master
              timeout-minutes: 5
            - run: |
                sudo docker build -t aerialist .
                cd ..
                sudo docker exec -it $(docker run --env-file .env -dit aerialist) bash
                python3 cli.py generate snippets/case_studies/mission1.yaml 4
              working-directory: ./snippets
            